<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lenovo-PC" failures="3" tests="12" name="RetryMultipleFailedTestCases" time="0.181" errors="0" timestamp="2020-07-11T23:29:49 IST">
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test1" time="0.014">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test1" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test1" time="0.006">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.TestNGRetryLogic.MyTest.Test1(MyTest.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test2" time="0.008">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.TestNGRetryLogic.MyTest.Test2(MyTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test3" time="0.001">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test3" time="0.004">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test3" time="0.002">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="com.TestNGRetryLogic.MyTest" name="Test3" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.TestNGRetryLogic.MyTest.Test3(MyTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
</testsuite> <!-- RetryMultipleFailedTestCases -->
